export const ACTIONS = {
  NO_OF_PAGES: "NO_OF_PAGES",
  NEWS_FEED: "NEWS_FEED",
  REMOVE_ARTICLE: "REMOVE_ARTICLE",
  HANDLE_SEARCH: "HANDLE_SEARCH",
  INCREMENT_PAGE: "INCREMENT_PAGE",
  DECREMENT_PAGE: "DECREMENT_PAGE",
  HANDLE_PAGE: "HANDLE_PAGE",
};
